### PR TITLE
Fixes #265 - Bed Verification Input Only

### LINKED ISSUE #265: Post Capture Library Pooling - Bed verification is not working
In this step there is no output plate, just tubes. So, we might add a new option to the script which allows to verify only the input bed, like '--only_input 1'.

### PR DESCRIPTION
**Pull request by jbeast**
Can now add `--input_only 1` flag to bed verifier epp. It will only
verify input plates

### CODE REVIEW

File: src/perl/lib/wtsi_clarity/process_checks/bed_verifier.pm [hunk 1]
```diff
@@ -117,9 +126,21 @@ sub _verify_plate_mapping {
...
+
+    if ($self->_input_only) {
+      $matches = grep { $_->{'source_plate'} == $plate_io->{'source_plate'} } @{$plate_mapping};
+
+      if ($matches != 1) {
+        croak "Expected source plate " . $plate_io->{'source_plate'};
+      }
+
+    } else {
+      $matches = grep { ($_->{'source_plate'} == $plate_io->{'source_plate'} && $_->{'dest_plate'} == $plate_io->{'dest_plate'}) } @{$plate_mapping};
```
Comment (ke4) [inline src/perl/lib/wtsi_clarity/process_checks/bed_verifier.pm]: Could you could DRY the above lines, please?
