### PR TITLE
Fixes #233 Added with_controls option to stamp epp

### LINKED ISSUE #233: Fluidigm Request (SM) - incorrect stamping
To correct this issue, we probably need to add a 'shadow_plate = 1' option to the stamping action.

### PR DESCRIPTION
**Pull request by jbeast**
By default we do not want to stamp controls. However, we want to
allow the ability to do so if required. Stamper will now not stamp
controls unless with_controls flag is set or it is a shadow stamp

### CODE REVIEW

File: src/perl/lib/wtsi_clarity/epp/generic/stamper.pm [hunk 1]
```diff
@@ -173,25 +180,29 @@ sub _build__analytes {
...
     my $container_url = $analyte_dom->findvalue($CONTAINER_PATH);
+
     if (!$container_url) {
       croak qq[Container not defined for $url];
     }
 
+    my @control_flag = $analyte_dom->findnodes($CONTROL_PATH);
+
+    # By default we do not want to stamp controls (unless it's a shadow plate)
+    if (@control_flag && !$self->with_controls && !$self->shadow_plate) {
```
Comment (ke4) [inline src/perl/lib/wtsi_clarity/epp/generic/stamper.pm]: I think this condition is not correct:
if with_controls => 1 and shadow_plate => 0 it will add the control, because the expression's result is false.

Comment (jbeast) [inline src/perl/lib/wtsi_clarity/epp/generic/stamper.pm]: I'm confused. We want to add the control if `with_controls => 1`

Comment (ke4) [inline src/perl/lib/wtsi_clarity/epp/generic/stamper.pm]: Sorry, I wrote the wrong thing, I meant:
if with_controls => 0 and shadow_plate => 1 it will add the control, because the expression's result is false.
